### ISSUE TITLE
Project Launch

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#1]
Just keeping track of the steps needed for project launch

 - [x]  GitHub Organization
 - [x]  Get non-profit rate w GH
 - [x]  Google site for welcoming new members (in progress)
 - [x]  Google site for project portal  (in progress)
 - [x]  Slack workspace
 - [x]  Google groups  (in progress pending feedback)
 - [ ]  SOPs (need a list of which SOPs are needed for this project, eg SOP on how to contact the stakeholders (see https://github.com/cancerDHC/Terminology/issues/3  )- create a google doc)
 - [x]  Project Calendar
- [x] Project Calendar Info
 - [x] Google drive folders and permissioning (in progress pending groups)
- [] ~Zoom room that is not tied to a specific person (anyone have this to offer institutionally?)~
 - [x] Populate GitHub with milestones and issues for project plan

**Comment by nicolevasilevsky** [comment]
@nicolevasilevsky - look into GH non-profit or free GitHub accounts

**Comment by nicolevasilevsky** [comment]
A list of SOPs that are needed is here:
https://docs.google.com/spreadsheets/d/1zOtgYhwrtJ4EDAbQSgFm9mqDz6pKMG8KnE1IjC9WAE8/edit#gid=0
