### ISSUE TITLE
1d1: Create timeline for web portal development

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#10]
landing page:
- [x] need content for the landing page @nicolevasilevsky. Will be a sub-tab of this page: https://datascience.cancer.gov/data-commons

Timeline:
- [x] create a google doc/spreadsheet with a timeline (@nicolevasilevsky)

**Comment by gaurav** [comment]
I think we decided that Chicago (@bfurner, @volcs0) would take the lead on this, and would coordinate with the NCI so we can get a simple website up as soon as possible. Is that right?

**Comment by nicolevasilevsky** [comment]
Sherri said she'll submit a request to systems folks and let them know that @bfurner is the point person

**Comment by nicolevasilevsky** [comment]
landing page:
- [ ] need content for the landing page @nicolevasilevsky. Will be a sub-tab of this page: https://datascience.cancer.gov/data-commons

**Comment by nicolevasilevsky** [comment]
[Website folder](https://drive.google.com/drive/folders/1Bdkfbws5Jsp5fuhL2IZtpfy95LeABCw-)
- [Landing page draft](https://docs.google.com/document/d/1B35RJKwiXYLCSESykBPc719h6V5_j2akUYGI3GsNWGg/edit)
- [Timeline for development](https://docs.google.com/spreadsheets/d/1DGPSHIasNs-DiC2J2cjX1uFi6BRtB2zkaRD3O-APXHk/edit#gid=0)

**Comment by nicolevasilevsky** [comment]
@bfurner I think this can be closed, yes?

**Comment by bfurner** [comment]
well, we've gotten an initial draft of a landing page to CBIIT thanks to your work.  

but we have not gotten very far at all on requirements and timeline for the portal per se.  what content needs to be on the portal?  who defines those requirements?  we'll need to know these things to get moving on a timeline.

**Comment by nicolevasilevsky** [comment]
Good question about the requirements and timeline for the web portal. I think that is on @balhoff's team. I'll reassign this to him, and remove the community dev WG tag.

**Comment by gaurav** [comment]
We had a meeting about planning the web portal on Friday; [meeting notes](https://docs.google.com/document/d/1WJ2zfwBDSRD9mhlvpZE-SQGf7DF5E_ybtkdvgF5Mshg/edit) are available. We decided to organize the website around the four workstreams, and to collaboratively make mockups of the website in Google Slides.

**Comment by nicolevasilevsky** [comment]
Timeline for web portal development [here](https://docs.google.com/spreadsheets/d/1STswBwkXjGg3PuiG9eW8q4euPUF3OontLGBQAVJgdgU/edit#gid=0)
