### ISSUE TITLE
1a3: Conduct interviews

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#11]
See [plan here](https://docs.google.com/document/d/1Es-IMNANW8xRvJWLmOLbV63gWWFFrSfhgTE2gHqKXak/edit)
1	DCF, HTAN, ICDC, IDC
2	GDC, PDC
3	CDA: Cancer Data Aggregator	Cloud Resources	Interoperability and Integration	Kids First DRC
4	Broad Firecloud	CIDC: Cancer Immunology Data Commons	Clinical Trials Data Commons	ISB-CGC	Semantic Infrastructure Team	SevenBridges
5	CDS: Cancer Data Services	CRDC Leadership & NCI Office of Data Sharing (data management policy & workflow)	External Communications Strategy for CRDC
6	National Biomedical Imaging Archive	SEER Virtual Tissue Repository

**Comment by keblumhardt** [comment]
Follow-up Interviews for DCF, HTAN, ICDC, GDC, PDC will be scheduled in the second and third week of February.
Prior to the follow-up interviews, a representative from each workstream will review notes from initial meeting and summarize remaining questions [here].(https://docs.google.com/spreadsheets/d/1NGuM7hjr8DNh4bB5AOVoZ3vHdTUNsOL1Uw_w9mea-UA/edit?folder=16p7J-toard1U9WpzrBNZXLb-RVuDT3qq#gid=0.)

**Comment by keblumhardt** [comment]
Will be scheduling meetings for Wave 4 after the pre-surveys come back. Interview tracking document [here](https://docs.google.com/document/d/18BDb1F1zvS1mXSkAbQJAzTNsDxnjCNAm-bXTRAYJbks/edit).

**Comment by nicolevasilevsky** [comment]
Who needs to be on the future meetings?
- prep meetings- invite the internal group?
- node interviews - who are the 'must-attend' folks?

**Comment by nicolevasilevsky** [comment]
Node interviews - ideally include everyone as we did before, Community Dev team, Brian, Sherri, Resham, Melissa are must-have

Earliest: 7am PT
Latest: 6pm ET

(9am - 4pm CT)

**Comment by monicacecilia** [comment]
- [x] 1 DCF, HTAN, ICDC, IDC
- [x] 2 GDC, PDC
- [x] 3 CDA: Cancer Data Aggregator Cloud Resources Interoperability and Integration Kids First DRC
- [ ] 4 Broad Firecloud CIDC: Cancer Immunology Data Commons Clinical Trials Data Commons ISB-CGC Semantic Infrastructure Team SevenBridges
- [x] 5 CDS: Cancer Data Services CRDC Leadership & NCI Office of Data Sharing (data management policy & workflow) External Communications Strategy for CRDC
- [ ] 7 National Biomedical Imaging Archive SEER Virtual Tissue Repository

**Comment by monicacecilia** [comment]
I would like to close this ticket before its birthday. 🎊 

@volcs0, @nicolevasilevsky - I cannot recall with certainty, but I believe that the possibility of an interview with SEER Virtual Tissue Repository was no longer on the books for Phase II? Is this correct? If so, should we close this ticket and create a reminder for an interview with collaborators from SEER (not considered a CRDC node) on a different ticket in the Community Development WS? If it is not correct, then what should our next steps be?

**Comment by nicolevasilevsky** [comment]
My understanding is we do no plan to interview SEER. Let's close, @volcs0 please reopen or create a new ticket if we do need to interview SEER, thanks!
