### ISSUE TITLE
1a7: Report of common and unique needs of each node

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#19]

**Comment by ShahimEssaid** [comment]
This needs some better definition and breakdown.  How can this fit into some other activity or document so things are not too fragmented and difficult to keep in sync?

**Comment by nicolevasilevsky** [comment]
The [requirements synthesis](https://docs.google.com/spreadsheets/d/1NGuM7hjr8DNh4bB5AOVoZ3vHdTUNsOL1Uw_w9mea-UA/edit#gid=0) document provides an overview of the node interviews to date, and summarizes and categorizes specific aspects of each node, to allow us to quickly make comparisons across nodes. This includes categories such as release/change management processes, standards that are used, and workflows such as quality control (QC) processes, submission and flow.
