### ISSUE TITLE
2a1: Create and maintain a Help desk

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#23]
## Superticket with information about creating and maintaining a Help desk.

The purpose of the help desk is to assist with data preparation, including assistance with mappings and transformations of terminologies and models, metadata validation or data annotation as needed. 

Creating and maintaining a Help desk requires to:
 - [x] Create an easy-to-contact Help desk: 
    - (slack [#helpdesk](https://cancerdhc.slack.com/archives/CPGG83HCG) channel has been created)
- [x] Announce to nodes our office hours for data harmonization support. 
    - _Question: how will this be implemented? Would members from other workstreams be available on zoom from certain hours?_
- [x] Communicate the support strategy (moved here from #31)
- [x] Assign someone to draft the text for the announcement that will be sent to the nodes
~~- [ ] Should @keblumhardt set up another meeting to present version 0.1 of the DHM to the nodes?~~
 - [x] Re-announce existence of Help desk to nodes after the v0.1 harmonized model has been drafted (after May 01)
        - ticket: https://github.com/cancerDHC/operations/issues/67
- [x] Create an engagement plan that spans CDA and CCDH (feedback from Phase I report).
     - ticket: https://github.com/cancerDHC/operations/issues/70

**Comment by nicolevasilevsky** [comment]
See #31

**Comment by nicolevasilevsky** [comment]
to do after Feb 10

**Comment by nicolevasilevsky** [comment]
@jmcmurry will draft the slide/text that will be sent to the nodes

**Comment by nicolevasilevsky** [comment]
[FAQ doc](https://docs.google.com/document/d/1ON5XET_pFceKEHc6x1sQkCpqV9vWGUG1qhnRlZpXYzo/edit)
