### ISSUE TITLE
2a2: Develop user support documentation and materials (Concierge Services)

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#24]
Due Month 18.

This ticket is part of the task 2a **Semantic Concierge Services Support and CRDC Node, DCF and DCC engagement**:
- Here 'user' means node representative. 
- This ticket can be closed when:
    - [x] the website / portal contains documentation or links to documentation about how nodes can use the tooling that is discoverable on the CCDH portal
   - [x] nodes have been invited to review this documentation. Node feedback on the documentation will be managed in separate issues.
-  [x] @nicolevasilevsky create a google doc for notes/ideas as we think of them. This can be an index of internal SOPs for each tool (as we build them).
- Documentation should initially be for contributors, then we should write documentation for their users, then later documentation should be generalizations that can be for anybody

~~Later we can move this to the website.~~

**Comment by nicolevasilevsky** [comment]
We should create an index of SOPs here: how to contact the stakeholders

**Comment by nicolevasilevsky** [comment]
I created a [folder](https://drive.google.com/drive/folders/1PnYJZXb398YA7_g6ha1K9uv8XFjPBQSN) for SOPs and Documentation.

We should list/index SOPs that are needed in this [spreadsheet](https://docs.google.com/spreadsheets/d/1zOtgYhwrtJ4EDAbQSgFm9mqDz6pKMG8KnE1IjC9WAE8/edit#gid=0)
