### ISSUE TITLE
2b1a: Create web portal v1

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#25]
Due Month 8.
A web portal is ....
This issue can be closed when CCDH has a web portal that:
a) is a place a node can go online to see our work
b) lets the nodes know where to go to get the tooling to help them with data harmonization
c) helps discover tooling related to data migration, annotation, and terminology services

**Comment by monicacecilia** [comment]
- Web portal has been completed. 
- Latest version (staging) is visible at https://ccdhportaldev.pedscommons.org/
- First release will go out on or around Friday 18-Dec. 
- Web portal release notes can be found [here](https://github.com/cancerDHC/community-development/blob/master/Changes.md).
- Will close as soon as portal is officially released by CBIIT.

**Comment by monicacecilia** [comment]
Hooraaaaayyyyyyyyy!!!!! 🎉 
The CCDH Web Portal was officially released on 8-Jan-2021. 
The vanity URL https://ccdh.cancer.gov redirects to https://harmonization.datacommons.cancer.gov

Great job, everyone! :bowtie:
