### ISSUE TITLE
2b1g: Work with nodes to map and transform data

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#26]
Depends on 2b1f #46 
Starts Month 7.
Due Month 13.

This issue can be closed when each of the following have worked with us and have transformed their data where possible OR where not possible we have documented the technical reasons for this eg: one or more of:
- not a high priority use case for that node
- too resource intensive
- harmonization would break some node-specific functionality
~~- [ ] DCF~~
~~- [ ] HTAN~~
~~- [ ] IDC~~
- [ ] ICDC
- [ ] GDC
- [ ] PDC

**Comment by bfurner** [comment]
Use our work with the CDA on their MVP as evidence of our work towards this deliverable

**Comment by bfurner** [comment]
Transformation and harmonization of instance data is outside our remit, but the mapping from source node to CDM / CRDC-H is certainly within our remit and ICDC, GDC, and PDC will be included in the end of Phase II deliverables.
