### ISSUE TITLE
1b: Plan for supporting core semantic standards and providing concierge service

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#31]
This will be for node representatives, not end users.

We have set up concierge services as:

- email address: ccdh-project-management@googlegroups.com
- Slack help desk

to do:
- [x] will add office hours at a later date
- [x] communicate support strategy to the nodes
- [x] need FAQ, document questions that we are asked and add them to FAQ (need a google doc, @nicolevasilevsky)

(FAQ should go on website, see #10)

**Comment by nicolevasilevsky** [comment]
Created a doc to document FAQs [here](https://docs.google.com/document/d/1ON5XET_pFceKEHc6x1sQkCpqV9vWGUG1qhnRlZpXYzo/edit), which we can add to the website (when it is up)

**Comment by keblumhardt** [comment]
Closing ticket, moved existing outstanding items to 2a1.
