### ISSUE TITLE
Synthesis of Specification gathering

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#32]
- [x]  Review interview notes and bin findings accordingly
- [ ]  Identify [here](https://docs.google.com/spreadsheets/d/1NGuM7hjr8DNh4bB5AOVoZ3vHdTUNsOL1Uw_w9mea-UA/edit?folder=16p7J-toard1U9WpzrBNZXLb-RVuDT3qq#gid=0) common categories of Node attributes and use cases that cut across nodes
- [ ]  Revise categories/annotations as needed

**Comment by keblumhardt** [comment]
Will update after additional interviews are completed.

**Comment by monicacecilia** [comment]
I think this is now part of E2E Assessment.

**Comment by nicolevasilevsky** [comment]
Yes, I think this can be closed
