### ISSUE TITLE
put up structure for storyboards

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#35]
@mellybelly was assigned to this action item at the F2F meeting too

**Comment by nicolevasilevsky** [comment]
See F2F notes for more info

**Comment by nicolevasilevsky** [comment]
Community workstream - fill in content for the storyboard

**Comment by nicolevasilevsky** [comment]
@DaveraGabriel is developing a story for CCDH, a tutorial is available, will draft a user story for data submitters.

Aiming for mid-Feb due date.

**Comment by nicolevasilevsky** [comment]
@DaveraGabriel please link to google docs on this ticket.

**Comment by nicolevasilevsky** [comment]
@DaveraGabriel is there any action required from anyone on the community development workstream?

**Comment by DaveraGabriel** [comment]
Hello @nicolevasilevsky ... perhaps the community development workstream can help me clarify an issue that came up when I shared the framework and draft userstory with the TermServices . data modeling group.  The only feedback I got back is that they were not sure / there was confusion about who the "user" is.  I built the framework based on Melissa's direction, to address the workflow for the node data uploaders.  The Data Modeling / Term Services group isn't sure whether those individuals are the primary users of the systems we are developing in favor of investigators / clinicians that are developing queries.  As such, Ive not developed any of the additional scenarios indicated in the framework until this is resolved.  I sent Melissa an eMail with a calendar entry for yesterday's Data Modeling / Term Services regular meeting with a time conversion for the UK (where Ive heard she is now) in hopes that should she attend a meeting where this topic is discussed, this could be cleared-up.  She wasn't able to attend, and so if the community development workstream could please take up the issue of who exactly we are building tools for - what workflow is intended to be addressed by the User Stories - that would be quite helpful, and provided I have the free time to do so, can bang-out the remaining stories in just a few hours.  Im not sure if the links to the artifacts on Googledocs added to the PDF will persist, if they do not I'll add them again Many thanks - D
[CCDH Draft User Story framework 31JAN2020.pdf](https://github.com/cancerDHC/operations/files/4185937/CCDH.Draft.User.Story.framework.31JAN2020.pdf)

**Comment by DaveraGabriel** [comment]
@nicolevasilevsky : the links did not confer....  Here are the links referenced in the eMail, in order represented in the text

Draft User Story: https://docs.google.com/document/d/1-5_6qW77V48aQpOfyNZQJI5rTS0ASa-h/edit

Worksheets with proposed framework:  https://docs.google.com/spreadsheets/d/1MhblAat5UvPMKtcfOl9Nhk1vHzZEiKr6yjlQ8pM82yU/edit#gid=0

Mini-persona document:  https://docs.google.com/document/d/1olHpDXGJnbTXcSb-sfJypiKjBmgyCXLm/edit

Your client question resource used for the basis of scenario variation development:  https://docs.google.com/document/d/1hPXfyeUaaEPNcH-qbUIqiyIOwEN2rT6Oj_Ym_KQrSks/edit

Please let me know if there are any trouble with the links or questions about the content of the proposal

**Comment by monicacecilia** [comment]
This is now being done as part of the E2E Requirements Assessment. 
@nicolevasilevsky, @DaveraGabriel - please be sure to update / close as appropriate. Thank you! 🌷
