### ISSUE TITLE
Community engagement plan for iterative feedback and implementation of model/terminology/services

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#36]
This call should happen in mid-Feb

~@monicacecilia to schedule date~

Community = CRDC community and data coordinating centers

@keblumhardt is scheduling dates for us to present to the nodes - mid-Feb and end of Feb. To do: 
- [x] @keblumhardt send out the calendar invites to CCDH internal. 
- [x] @volcs0 and @nicolevasilevsky draft email to invite the nodes (share with @mellybelly before sending)

**Comment by nicolevasilevsky** [comment]
Community = CRDC community and data coordinating centers

@keblumhardt is scheduling dates for us to present to the nodes - mid-Feb and end of Feb. To do: 
- [ ] @keblumhardt send out the calendar invites to CCDH internal. 
- [ ] @volcs0 and @nicolevasilevsky draft email to invite the nodes (share with @mellybelly before sending)

**Comment by nicolevasilevsky** [comment]
Draft email here: https://docs.google.com/document/d/1yaJNTZkFiXybr1t4K5MOup6Q-YynjKJBvlCfhTrTlB0/edit

**Comment by nicolevasilevsky** [comment]
@cgchute @bfurner @volcs0 could you please review/edit/add content to the draft email above?
thanks!

**Comment by cgchute** [comment]
Looks basically good.  i would not be so direct as "which can be used by nodes."  Perhaps   "as a step toward a shared model that could be used by nodes?"

**Comment by nicolevasilevsky** [comment]
Thanks @cgchute!

**Comment by nicolevasilevsky** [comment]
the calls are scheduled, I think this can be closed
