### ISSUE TITLE
create GH issue(s) to discuss change management

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#37]
this was noted in the f2f meeting [notes](https://docs.google.com/document/d/18u0dFnO2KB0-Ni0dFewIy11RvQsDCGm5s4n4eK2Y9VQ/edit#)

**Comment by nicolevasilevsky** [comment]
Shahim, if this doesn't really make sense as a ticket, then feel free to close.

**Comment by monicacecilia** [comment]
Closing - I believe this went stale.
