### ISSUE TITLE
SWOT for each node

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#38]
dependent on #32 
Document is [here](https://docs.google.com/document/d/1NL4zn1j-ZB3y0SdJf8Gw77m0Tcx9g1gFx8WVfFFmG3Y/edit?folder=16p7J-toard1U9WpzrBNZXLb-RVuDT3qq); for now this is controlled access, but it will be shared when ready.

**Comment by jmcmurry** [comment]
Informally and partially done as part of ongoing conversations with nodes. Per discussion with @mellybelly, we have decided not to further pursue a formal SWOT because the requirements analysis was both robust and fit-for-purpose.
