### ISSUE TITLE
Make cmap for each Wave 1 data model

### ISSUE THREAD

**Issue by diatomsRcool** [cancerDHC/operations#41]
For each data model make a cmap in draw.io. The cmap should have boxes for entities and arrows for relationships. All entities and relationships should be labeled according to the node documentation. The total number of properties and relationships for each entity should be added, in parentheses, after the entity label. Try to organize the diagram so no arrows cross each other.
This issue can be closed when there is a cmap for: 
- [x] GDC - Matt, Brian
- [x] PDC - Shahim, Nicole
- [x] ICDC - Maura, Anne

**Comment by jmcmurry** [comment]
@tricfran to update assignments here.
