### ISSUE TITLE
document discrepancies, inconsistencies, or gaps within each node

### ISSUE THREAD

**Issue by diatomsRcool** [cancerDHC/operations#44]
Make an assessment as to whether a gap identified in a node (eg. we have a core element or relationship that isn't in the node) it is something that
a) we advise be addressed directly by the node,
b) we accommodate in some way centrally
c) we formally determine that neither a nor b is in scope

This issue can be closed when all gaps have been assessed as either a, b, or c. The final assessment is available via <what form should this take?>.

**Comment by monicacecilia** [comment]
@diatomsRcool I think the answer to 'what form should this take' is: E2E Requirements Assessment. What do you think?

**Comment by diatomsRcool** [comment]
What for will the E2E Requirements Assessment take? A narrative doc? A spreadsheet?

**Comment by monicacecilia** [comment]
The End-to-End Assessment addressed this issue. A copy of this document can be found [here](https://drive.google.com/drive/folders/1eeRn1Wdbh4xkmfHj3HgUxJbP98xA44pg).
:bowtie:
