### ISSUE TITLE
Requirements gathering from nodes

### ISSUE THREAD

**Issue by mellybelly** [cancerDHC/operations#5]
We need to start gathering materials, familiarizing ourselves with the models, terminologies and the data in each node. Some things to collect in advance of scheduling the discussions:

- [ ] data model (even if draft)
- [ ] documentation
- [ ] terminologies
- [ ] sample data
- [ ] competency questions
- [ ] licensing 
- [ ] Aims or proposal

**Comment by mellybelly** [comment]
Please create a new repo for these materials, also ask if it is ok to make them public before doing so.

**Comment by mellybelly** [comment]
can also go in google drive for now, but eventually we'll want public documentation in github.

**Comment by jmcmurry** [comment]
We now have a privately-shared [gDrive folder](https://drive.google.com/drive/u/0/folders/16p7J-toard1U9WpzrBNZXLb-RVuDT3qq) for collecting this info and we have a [requirements draft roadmap](https://docs.google.com/document/d/1HS_NAntAQf22Xyk9_Rx0jdwScdRooUPhc__PJyQ4T4k/edit#heading=h.3fy0zmwexoe1). I think we can close this ticket and open one which is more about the execution than the prep.
