### ISSUE TITLE
Name project drivers / milestones which create timeframe for completion of Operations issue #48

### ISSUE THREAD

**Issue by DaveraGabriel** [cancerDHC/operations#51]
There is a need to more fully define the parameters around this work in order to efficiently deliver resolutions.  This issue is aimed at understanding the timing vector / axis to effectively scope and then prioritize completion.  Please identify the CCDH project deliverable which lead to the necessity of delivering this work and the date by and after which this deliverable impacts said, identified CCDH project deliverable.

**Comment by monicacecilia** [comment]
@monicacecilia to close when #48 is completed.

**Comment by monicacecilia** [comment]
😬
