### ISSUE TITLE
Development of User Stories / Storyboards for CCDH Use Cases

### ISSUE THREAD

**Issue by DaveraGabriel** [cancerDHC/operations#52]
Follow-up to HOT F2F meeting, HOT use cases appropriate for CCDH to be tracked here

**Comment by DaveraGabriel** [comment]
@volcs0 :  can you or your designee please help develop a good short list of the 'Node Archetypal' personas?  what's a good starting list of the kinds of people that are our CCDH node clients?  I have the following (naive) list:

1) database administrator
2) data curator
3) node administrator

... who should be our client targets?  
Many thanks
Davera

**Comment by DaveraGabriel** [comment]
@volcs0 Hello Sam:  I located this list of "users" in the NCI Query Workshop deliverables Google worksheet.  Is this a good working list, or are there too many?  Can nay of these be collapsed / consolidated?

Basic Researcher
Basic Scientist
Bioinformatician
Biologist
Classmate
Clinical Researcher
Clinician
Computational Biologist
Data Coordinator
Epidemiologist
Insurance
Pathologist
Patient
Policy Maker
Program Manager
Radiologist
Reporter
Reporter
Researcher
Software Developer
Statistician

**Comment by monicacecilia** [comment]
I think this is a dup of #35 - and the topic is being addressed on the current E2E assessment. Closing in favour of additional info on #35.
