### ISSUE TITLE
Plan a face to face meeting with the nodes

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#54]
Could be piggy backed on another CRDC event or other NIH event. There is planning for a CRDC meeting (sometime after June, date is not set yet)

Probably aim to do this in the next year (late 2020- early 2021).

Should do this after CDA is up and running.

**Comment by nicolevasilevsky** [comment]
This is happening June 29-20, I am on the planning committee.

**Comment by nicolevasilevsky** [comment]
Action item: decide who will attend in person

**Comment by nicolevasilevsky** [comment]
- [ ] add as agenda item for Wed meeting @nicolevasilevsky

**Comment by jmcmurry** [comment]
As the basics of the timing and attendees are now settled, I will mark this complete. @nicolevasilevsky you're of course free to add any additional related issues as needed.
