### ISSUE TITLE
1a1: Review existing node materials

### ISSUE THREAD

**Issue by jmcmurry** [cancerDHC/operations#6]
Review existing materials and understand their purpose with NCI staff and other stakeholders

We are done with the first round of this, but will leave it open until complete.

**Comment by ShahimEssaid** [comment]
I think this implies some of the following sub tasks but there must be some goal other than just us individually reviewing materials. Were can we capture what we've reviewed? There are few existing documents that should probably be updated along with the review. For example, @nicolevasilevsky sheets capturing queries, terminologies, etc.  Let's also list (in this issue) the various documents that need to be created or updated during this review and in the future.

Sub tasks:

- [ ] documentation on websites
- [ ] pre interview questionnaire
- [ ] first round interview notes
- [ ] preparation for round two
- [ ] ?

Relevant docs:

**Comment by nicolevasilevsky** [comment]
Each workstream reviewed the preliminary materials that were shared by each node in preparation for each interview, and this is documented in our notes in [google drive](https://drive.google.com/drive/folders/16p7J-toard1U9WpzrBNZXLb-RVuDT3qq).
