### ISSUE TITLE
Deep dive into the Portable Format for Biomedical (PFB)

### ISSUE THREAD

**Issue by gaurav** [cancerDHC/operations#62]
We need to do a deep dive into the Portable Format for Biomedical (PFB) and figure out a few things:
- [x] Create some FAQs about this format for our website
- [x] Figure out what we would do if people wanted to bring us PFB files: would we convert it into the harmonized model, validate it, or what?
  - There might be a connection with [CEDAR](https://metadatacenter.org/) here -- can PFB be used to move caDSR valuesets around? Could data collected through CEDAR be exported as PFB?
- [x] Look for other formats that can be used to move bundles of data around, such as PFB. 

Brief description of PFB: PFB is an Avro-based serialization format with a specific schema to import, export and evolve biomedical data. PFB specifies metadata and data in one file. Metadata includes data dictionary, ontology references & relations between nodes. It is part of Gen3 (an open source software platform for developing and operating data commons). It is primarily used to move large chunks of data and metadata from one of their supported systems/commons to another.  It also seemed useful for saving ‘snapshots’ in time. See also [this article](https://ascopubs.org/doi/abs/10.1200/JCO.2019.37.15_suppl.e18094).

Some resources on PFB:
- [Hughes et al, 2019](https://ascopubs.org/doi/abs/10.1200/JCO.2019.37.15_suppl.e18094)
- pyPFB on [Github](https://github.com/uc-cdis/pypfb) and [PyPI](https://pypi.org/project/pypfb/).

**Comment by gaurav** [comment]
I've written up [a description of PFB](https://docs.google.com/document/d/1Smz0DoVO22FN-W__l_N-9nPhkw973PT_1R4z_-DM76Y/edit#) in our shared Google Drive and added it to the [CCDH Tools Landscape document](https://docs.google.com/document/d/1g1b3jLQcyrJFT9NyKj0L9rTL6L3DLhHr_lw8Da2UrNs/edit#) -- have a look and let me know if you have any outstanding questions! I'll keep looking for other formats that could serve the same purpose as PFB. If there are no follow-up questions in a week or so, I think it'll be time to close this issue.

**Comment by TomConlin** [comment]
+1.

I worry a bit about the absolute v.s. relative clarity of:

```
 "tobacco_smoking_onset_year": 76,
      "tobacco_smoking_quit_year": 63,
```

**Comment by gaurav** [comment]
Tom: those terms are coming from [caDSR 2228604](https://cdebrowser.nci.nih.gov/CDEBrowser/search?elementDetails=9&FirstTimer=0&PageId=ElementDetailsGroup&publicId=2228604&version=1.0) and [caDSR 2228610](https://cdebrowser.nci.nih.gov/CDEBrowser/search?elementDetails=9&FirstTimer=0&PageId=ElementDetailsGroup&publicId=2228610&version=1.0) respectively, as per the [metadata included in the Avro file](https://gist.github.com/gaurav/a77dc4199568f8a9557ae452fa5e0976#file-pfb-dd_100-avro-metadata-json-L1505-L1523). I think users can pick other terms if they prefer?

On Slack, @TomConlin pointed me to [OMOP](https://www.ohdsi.org/data-standardization/the-common-data-model/) as another potential data exchange format, but I'm not sure if it includes a format or just a common data model (in which case, the CCDH Harmonized Model will provide a common data model better suited for our needs?). Apart from that, I couldn't find any other generic biomedical data exchange formats, so I think we're ready to close this issue unless anybody else has anything to add?

**Comment by gaurav** [comment]
At our last internal meeting (June 3, 2020), we decided that this level of detail was good enough for now. We can reopen this issue when a need for PFB arises in our project.
