### ISSUE TITLE
Select a modeling language in which to represent the CRDC-H model

### ISSUE THREAD

**Issue by bfurner** [cancerDHC/operations#64]
Candidate languages include:

- FHIR
- BioLinkML
- UML

**Comment by gaurav** [comment]
Do we want to consider [Bento MDF](https://github.com/CBIIT/bento-mdf/)? That's the format used to record [ICDC's model](https://github.com/CBIIT/icdc-model-tool/tree/master/model-desc) and [CTDC's model](https://github.com/CBIIT/ctdc-model/tree/master/model-desc).

**Comment by bfurner** [comment]
We should certainly assess Bento using the same criteria we use to assess the others.  Thanks Gaurav.

**Comment by gaurav** [comment]
I think we can close this because of https://github.com/cancerDHC/data-model-harmonization/issues/9?

**Comment by monicacecilia** [comment]
Yassss! :bowtie: 
The data model harmonization workstream will be making use of BiolinkML as the language in which to express its model for the initial MVP work with the CDA. They will evaluate this decision at the end of the MVP work.
