### ISSUE TITLE
rename node specific channels in Slack

### ISSUE THREAD

**Issue by nicolevasilevsky** [cancerDHC/operations#78]
Description: 
rename node specific channels in Slack:
#idc-data-model
#htan-technical-data-model
#htan-data-model
#cda-and-ccdh 
and others

Rename to more general names.

I sent a message in the Internal channel on 09/29.

Who has admin access? I can't change the names.

**Comment by monicacecilia** [comment]
Welp. I guess I have some admin permissions, but I don't have superpowers. 
I just discovered that unless I was the one who created the channel I want to edit, I cannot change its name. 
Perhaps @jmcmurry has superpowers we can inherit?

**Comment by nicolevasilevsky** [comment]
@keblumhardt this should go into the newsletter

**Comment by monicacecilia** [comment]
:bowtie:
