### ISSUE TITLE
2b1h: Develop and extend CRDC-H for use in the primary CRDC nodes

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/operations#83]

**Comment by bfurner** [comment]
The scope of this may need to be revised to be for use in the CDA as node adoption of the CRDC-H is likely a longer-term strategic aim.

**Comment by bfurner** [comment]
Finish Administrative and Biospecimen subdomain, and include Clinical subdomain

**Comment by monicacecilia** [comment]
updated in Phase II report.
