### ISSUE TITLE
2b1j, k, l: Create a semi-automated workflow for mapping and transformation for new data

### ISSUE THREAD

**Issue by monicacecilia** [cancerDHC/operations#85]
~~- [ ] 2b1j: Create a semi-automated workflow for mapping and transformation for new data, based on what we learned working with the nodes~~
~~- [ ] 2b1k: Make this tool accessible and functional in the web portal~~
~~- [ ] 2b1l: Incorporate automated provenance tracking for tool~~

**Comment by monicacecilia** [comment]
@gaurav, @bfurner - I assume we can consider this 'completed' - yes?

**Comment by bfurner** [comment]
i will defer to @gaurav on this one

**Comment by monicacecilia** [comment]
Removed in previous BAFO response.
